services:
  postgres:
    image: postgres:16
    container_name: pg-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-net
  minio:
    image: minio/minio:latest
    container_name: minio-container
    environment: 
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - app-net

  rust:
    build:
      context: ./rust-worker
    container_name: rst-container
    environment:
      DATABASE_URL: ${DATABASE_URL}
      #ACCOUNT_ID: ${ACCOUNT_ID}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
    depends_on:
      - postgres
      - minio
    networks:
      - app-net

  fastapi:
    build:
      context: ./fastapi
    container_name: fastapi-container
    environment:
      DATABASE_URL: ${DATABASE_URL_ASYNCPG}
      # ACCOUNT_ID: ${ACCOUNT_ID}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      #SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
    ports:
      - "8001:80"
    depends_on:
      - rust
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
