services:
  postgres:
    image: postgres:16
    container_name: pg-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:latest
    container_name: minio-container
    environment: 
      MINIO_ROOT_USER: ${ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${SECRET_ACCESS_KEY}
    volumes:
      - ./minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    restart: unless-stopped

  rust:
    build:
      context: ./rust-worker
    container_name: rst-container
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ACCOUNT_ID: ${ACCOUNT_ID}
      ACCESS_KEY_ID: ${ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
      MINIO_ENDPOINT: http://minio-container:9000
    depends_on:
      - postgres
      - minio

  fastapi:
    build:
      context: ./fastapi
    container_name: fastapi-container
    environment:
      DATABASE_URL: ${DATABASE_URL_ASYNCPG}
      ACCOUNT_ID: ${ACCOUNT_ID}
      ACCESS_KEY_ID: ${ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
    ports:
      - "8001:80"
    depends_on:
      - rust
